#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url : jdbc:mysql://127.0.0.1:3306/TailFriend
#    username: tailfriendManager
#    password: Dlehdgns0126!
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://db-i202p.pub-cdb.ntruss.com:3306/kkorifriend?characterEncoding=utf8
    username: kkorifriend
    password: kkorifriend123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 1024